version: '3.2'

volumes:
  postgres_data_dev: {}
  redis_data: {}

services:

  postgres:
    build: ./devops/docker/postgres
    restart: always
    volumes:
      - postgres_data_dev:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
      POSTGRES_PASSWORD: secret
    command: -c fsync=off -c synchronous_commit=off -c full_page_writes=off
    networks:
      - default

  redis:
    restart: always
    build:
      context: ./devops/docker/redis/
    volumes:
      - redis_data:/data
    networks:
      - default


networks:
  default:
