version: "3.2"

volumes:
  postgres_data: {}
  redis_data: {}

services:
  postgres:
    build: ./devops/docker/postgres
    restart: on-failure
    container_name: ${PROJECT_NAME}_postgres
    image: ${PROJECT_NAME}_postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${PROJECT_NAME}
      POSTGRES_DB: ${PROJECT_NAME}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    command: -c fsync=off -c synchronous_commit=off -c full_page_writes=off
    networks:
      - default
    ports:
      - "${POSTGRES_PORT}:5432"

  redis:
    restart: on-failure
    container_name: ${PROJECT_NAME}_redis
    image: ${PROJECT_NAME}_redis
    build:
      context: ./devops/docker/redis/
    volumes:
      - redis_data:/data
    networks:
      - default
    ports:
      - "${REDIS_PORT}:6379"

networks:
  default:
    ipam:
      driver: default
