version: '3.2'

volumes:
  postgres_data: {}
  redis_data: {}

services:

  postgres:
    build: ./devops/docker/postgres
    restart: always
    container_name: ${PROJECT_NAME}_postgres
    image: ${PROJECT_NAME}_postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: ${PROJECT_NAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    command: -c fsync=off -c synchronous_commit=off -c full_page_writes=off
    networks:
      - default

  redis:
    restart: always
    container_name: ${PROJECT_NAME}_redis
    image: ${PROJECT_NAME}_redis
    build:
      context: ./devops/docker/redis/
    volumes:
      - redis_data:/data
    networks:
      - default


networks:
  default:
